// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs(id, created_at, updated_at, title, job_role, job_category ,company_name, location, salary, qualification, experience, last_date, description, apply_url)
VALUES($1, $2 ,$3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
    RETURNING id, created_at, updated_at, title, job_role, job_category, company_name, location, salary, qualification, experience, last_date, description, apply_url, is_active
`

type CreateJobParams struct {
	ID            pgtype.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Title         string
	JobRole       string
	JobCategory   pgtype.Text
	CompanyName   string
	Location      string
	Salary        pgtype.Text
	Qualification string
	Experience    string
	LastDate      string
	Description   string
	ApplyUrl      string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.JobRole,
		arg.JobCategory,
		arg.CompanyName,
		arg.Location,
		arg.Salary,
		arg.Qualification,
		arg.Experience,
		arg.LastDate,
		arg.Description,
		arg.ApplyUrl,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.JobRole,
		&i.JobCategory,
		&i.CompanyName,
		&i.Location,
		&i.Salary,
		&i.Qualification,
		&i.Experience,
		&i.LastDate,
		&i.Description,
		&i.ApplyUrl,
		&i.IsActive,
	)
	return i, err
}

const getAllJobs = `-- name: GetAllJobs :many
SELECT id, created_at, updated_at, title, job_role, job_category, company_name, location, salary, qualification, experience, last_date, description, apply_url, is_active FROM jobs
WHERE is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) GetAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.JobRole,
			&i.JobCategory,
			&i.CompanyName,
			&i.Location,
			&i.Salary,
			&i.Qualification,
			&i.Experience,
			&i.LastDate,
			&i.Description,
			&i.ApplyUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const geyJobById = `-- name: GeyJobById :one
SELECT id, created_at, updated_at, title, job_role, job_category, company_name, location, salary, qualification, experience, last_date, description, apply_url, is_active FROM jobs WHERE id = $1 LIMIT 1
`

func (q *Queries) GeyJobById(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, geyJobById, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.JobRole,
		&i.JobCategory,
		&i.CompanyName,
		&i.Location,
		&i.Salary,
		&i.Qualification,
		&i.Experience,
		&i.LastDate,
		&i.Description,
		&i.ApplyUrl,
		&i.IsActive,
	)
	return i, err
}
