// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID            pgtype.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Title         string
	JobRole       string
	JobCategory   pgtype.Text
	CompanyName   string
	Location      string
	Salary        pgtype.Text
	Qualification string
	Experience    string
	LastDate      string
	Description   string
	ApplyUrl      string
	IsActive      pgtype.Bool
}
